### ISSUE TITLE
Chaotic mouse behaviour under KDE

### ISSUE THREAD

**Issue by v-fox** [smplayer-dev/smplayer#272]
**Describe the bug**

9 out of 10 clicks on anywhere, besides buttons, in smplayer's window forces mouse position to top-left corner of the window and switches it into drag-mode.

**To Reproduce**
1. Just click anywhere

**Expected behavior**
Not teleporting cursor or jerking window around.

**Screenshots**

**Your Enviroment**
 - SMPlayer version: 21.10.0 but also affect several past versions
 - OS: openSUSE Tumbleweed / rolling release
 - Multimedia engine you're using with SMPlayer (preferences -> general):
 [ ] MPlayer
 [X] MPV

**Logs**
[smplayer.log](https://github.com/smplayer-dev/smplayer/files/7489981/smplayer.log)

**Additional context**
KDE in general has this problem but it usually manifests by double-clicking on empty places in windows which switches cursor into drag-mode despite there not being such "feature" in `systemsettings5`, AFAIK. But smplayer brings it a step further by doing it on any click while also teleporting cursor. Settings of 'double click' and 'drag function' do not seem to matter.

**Comment by smplayer-dev** [comment]
I'm testing right now on KDE Neon and I'm afraid I can't see this problem. Clicking works as expected.

**Comment by v-fox** [comment]
> I'm testing right now on KDE Neon and I'm afraid I can't see this problem. Clicking works as expected.

I tried flipping some settings some more and determined that this happens when KDE"s default style "Breeze" is selected. With "Oxygen" it only sticks into drag-mode but not teleports, with "QtCurve" half of clicks just get ignored and only "Fusion" works fine.

Pause/unpause takes about second of delay after clicking and is ignored while dragging. But that's irrelevant to the main issue and is probably a side-effect of "drag function" feature which I don't use. But would be nice if in "none" it would allow pause/unpause on dragging click because it's hard to avoid all movement while clicking on a high-sensitivity gaming mouse.

**Comment by Scheirle** [comment]
> I'm testing right now on KDE Neon and I'm afraid I can't see this problem. Clicking works as expected.

I have this issue too on both KDE Neon / Manjaro since quite a while, maybe some visualization helps:
Precise click (works as expected):
![record-2022-07-31_11 13 56 mkv](https://user-images.githubusercontent.com/4129744/182020399-ee986c02-5dea-4f1b-9c06-3e2dca333719.gif)

Miss/screen click (+mouse move) moves the whole window and mouse jumps to the top corner:
![record-2022-07-31_11 14 02 mkv](https://user-images.githubusercontent.com/4129744/182020442-223c5fa3-ae6f-4ed1-b881-31a4294ecd5c.gif)
![record-2022-07-31_11 14 11 mkv](https://user-images.githubusercontent.com/4129744/182020445-36659705-15e5-4d81-8beb-4aa0f929d7b7.gif)

"Drag function" is set to "None" in all cases.
SMPlayer version: 22.7.0 (Revision 10091)

**Comment by BenjaminRi** [comment]
I tracked the issue down to the following line of code:

https://github.com/smplayer-dev/smplayer/blob/738f87bad419ddcfcac4094111c826b102fb201f/src/core.cpp#L1863

The root cause is the call to `winId()`. Surprisingly, this does way more than just getting a window ID. As documented in the QWidget Class: https://doc.qt.io/qt-6/qwidget.html#winId

> If a widget is non-native (alien) and winId() is invoked on it, that widget will be provided a native handle.

It turns the widget into a native one, so it does a whole bunch of stuff under the hood. One of the things it does must be breaking various events and cursor position variables.

Unfortunately, we can't just omit that line, or else the video will play in a separate, popped out window. I suspect that this bug might not even be in SMPlayer itself, but instead in the KDE or Qt libraries.

Note that VLC media player also exhibits the same issues.

**Comment by BenjaminRi** [comment]
The erratic behavior can be disabled in the KDE system settings:

`System Settings` -> `Appearance` -> `Application Style` -> (press edit button on the bottom right of the selected style) -> `General` tab -> Set `Windows' drag mode` to `Drag windows from titlebar only`

Note that this behavior (and whether this setting exists) is completely dependent on the selected application style.

(Original instructions found at: https://forum.kde.org/viewtopic.php?f=289&t=136450 )

It seems to me that this feature (and some bugs surrounding it and `winId()`) is the root cause of the issue.

It also seems to me that this is something that should be fixed in KDE Plasma, but perhaps applications like SMPlayer could work around it by catching mouse events on empty areas, thus disabling this feature on all relevant surfaces.

**Comment by BenjaminRi** [comment]
Interestingly, on Ubuntu 22.04 LTS, this bug is present on the KDE _Breeze_ (v5.24.7-0ubuntu0.1) application style, but not on the _Oxygen_ (v5.24.6-0ubuntu0.1) one which has the same `Windows' drag mode` setting.

On Ubuntu 22.10, the bug is even worse. Instead of the mouse pointer, the entire window jumps to the erroneous position. Both _Breeze_ and _Oxygen_ are v5.25.5-0ubuntu1, and _Oxygen_ is once again unaffected.

So it must be a bug in how the _Breeze_ application style implements this move feature.

**Comment by v-fox** [comment]
> So it must be a bug in how the Breeze application style implements this move feature.

This whole damn "feature" is a bug, just like other stupid crap such as "activities", "aconadi meta-search engine" and its stupid hang-prone background processes and useless fat-ass databases! For years I couldn't figure out why the hell windows under KDE are getting "sticky", randomly go all over the place or un-maximize seemingly without any relevant options in kwin's (you know, the "Kde WINdows manager") settings and this seems to be the culprit.

**Comment by BenjaminRi** [comment]
> This whole damn "feature" is a bug

The fact that the mouse pointer (or even the entire window) jumps is a bug indeed. The _Oxygen_ application style does not have this issue.

The other things you mentioned are indeed features, though it's debatable whether they have any use or just cause inconveniences.

**Comment by BenjaminRi** [comment]
I now created a KDE Plasma bug: https://bugs.kde.org/show_bug.cgi?id=468361

I think this issue can be closed on SMPlayer's side, as it is not at fault.

**Comment by v-fox** [comment]
> I think this issue can be closed on SMPlayer's side, as it is not at fault.

I guess that's right.
Thanks for the investigation. You've saved us all here a ton of trouble in general, not just player-related.

**Comment by CotyTernes** [comment]
> The erratic behavior can be disabled in the KDE system settings:
> 
> `System Settings` -> `Appearance` -> `Application Style` -> (press edit button on the bottom right of the selected style) -> `General` tab -> Set `Windows' drag mode` to `Drag windows from titlebar only`
> 
> Note that this behavior (and whether this setting exists) is completely dependent on the selected application style.
> 
> (Original instructions found at: https://forum.kde.org/viewtopic.php?f=289&t=136450 )
> 
> It seems to me that this feature (and some bugs surrounding it and `winId()`) is the root cause of the issue.
> 
> It also seems to me that this is something that should be fixed in KDE Plasma, but perhaps applications like SMPlayer could work around it by catching mouse events on empty areas, thus disabling this feature on all relevant surfaces.

Thank you for posting this. I've been super annoyed by this behavior and after doing some web searching found this thread and have now made the settings change. Hopefully this works for me.
