### ISSUE TITLE
After updating the mpv, the gpu usage for playing the same video is several times higher than before

### ISSUE THREAD

**Issue by DreamMaoMao** [smplayer-dev/smplayer#886]
**Describe the bug**

Play the same video:
Before mpv update :15%
After mpv update :70%

This makes computers very clunky.

**To Reproduce**
1. play a video and use nvtop command to watch gpu usage
2. update mpv
3. play the same video and use nvtop command to watch gpu usage

**Expected behavior**

**Screenshots**
![image](https://github.com/smplayer-dev/smplayer/assets/30348075/c8e043cf-d5a1-4e19-a95e-6c0920a8e270)

**Your Enviroment**
 - SMPlayer version:
版本: 23.12.0 (修订版 10207)
使用 Qt 5.15.12 (用 Qt 5.15.11 编译)
使用 MPV v0.37.0

 - OS: 
 Arch Linux x86_64

 - Multimedia engine you're using with SMPlayer (preferences -> general):
 MPV

**Logs**
[mpv.log](https://github.com/smplayer-dev/smplayer/files/13930241/mpv.log)

**Additional context**

**Comment by DreamMaoMao** [comment]
Is it possible that some parameters need to be adjusted by smplayer?

**Comment by DreamMaoMao** [comment]
Rollback version to mpv 0.36.0
版本: 23.6.0 (修订版 10157)
使用 Qt 5.15.11 (用 Qt 5.15.10 编译)
使用 MPV 0.36.0

![image](https://github.com/smplayer-dev/smplayer/assets/30348075/2051b65c-25ef-47b6-b346-296e85a2fe09)

**Comment by Raza-0007** [comment]
This is not a bug, its by design. And it has nothing to do with smplayer. 

Mpv 0.37 uses higher quality shaders and scalers by default. These are computationally heavy, but provide better quality visuals. This was done after lengthy discussions on mpv page. The old defaults were moved into a new profile called `--profile=fast`. 

You can either use `-profile=fast` with smplayer or pass the profile's entire parameters to smplayer `-scale=bilinear -dscale=bilinear -dither=no -correct-downscaling=no -linear-downscaling=no -sigmoid-upscaling=no -hdr-compute-peak=no -allow-delayed-peak-detect=yes`

~Raza

**Comment by DreamMaoMao** [comment]
Well, it's much better with this parameter
